cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail , name='cart_detail'),
    path('<int:product_id>/' , views.cart_add , name='cart_add'),
    path('remove/<int:product_id>/' , views.cart_remove , name='cart_remove'),
]

coupons/urls.py
from django.urls import path
from . import views


app_name = 'coupons'

urlpatterns = [
    path('apply/' , views.coupon_apply , name='apply'),
    path('get-coupon/' , views.get_coupon , name='get_coupon')
]

main_store/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

admin.site.index_title = "Promo"
admin.site.site_header = "Promo Admin"
admin.site.site_title = "Promo-Ecommerce"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/' , include('accounts.urls' , namespace='accounts')),
    path('contact-us/' , include('contactus.urls' , namespace='contactus')),
    path('cart/' , include('cart.urls' , namespace='cart')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('orders/' , include('orders.urls' , namespace='orders')),
    path('' , include('store.urls', namespace='store')),
    path('join-US-seller/' , include('seller.urls' , namespace='seller')),
    path('seller/account/' , include('seller_account.urls' , namespace='seller_account')),


]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/' ,views.order_create , name='order_create'),
    path('traking-order/' , views.user_orders , name='traking'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf , name="admin_order_pdf"),
    
]

seller/urls.py
from django.urls import path
from . import views


app_name = 'seller'


urlpatterns = [
    path('why-us/' , views.why_us , name='why_us'),
    path('download-pdf/', views.download_pdf, name='download_pdf'),
    path('dashboard' , views.dashboard , name='dashboard'),
    path('my-products/' , views.products , name='products'),
    path('successfully/' , views.successfully , name='successfully'),
    path('analytics/' , views.analytics , name='analytics'),
    path('<int:id>/update-product/' , views.update , name='update'),
    path('delete/<int:id>/' , views.delete , name='delete'),
    path('order/<int:id>/delete/', views.order_delete, name='order_delete'),





    

]

store/urls.py
from django.urls import path
from . import views



app_name = 'store'


urlpatterns = [
    path('' , views.product_list , name='product_list'),
    path('products/' , views.store , name='products'),
    path('category/<slug:category_slug>/' , views.store , name='product_by_category'),
    path('<slug:category_slug>/' , views.product_list , name='product_list_by_category'),
    path('<int:id>/<slug:slug>/' , views.product_detail , name='product_detail'),
    path('<int:product_id>/comment/' , views.product_comment , name='product_comment')
    

]

templates/includes/alerts.html
{% if messages %}
    {% for message in messages %}
        <div id="message" class="container">
            <div {% if message.tags %}class="alert alert-{{ message.tags }}"{% endif %} role="alert">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
                {{ message }}
            </div>
        </div>
    {% endfor %}
{% endif %}

templates/includes/comment_form.html
{% block content %}





<div class="col-md-6">
    <h4 class="mb-4">Add A New comment</h4>
 
    <form aciton="{% url 'store:product_comment' product.id %}"  method='POST'>
        {{ form.as_p }}
        {% csrf_token %}
        <div class="form-group mb-0">
            <input type="submit" value="Add Comment" class="btn btn-primary px-3">
        </div>
    </form>
</div>


{% endblock content %}

templates/includes/footer.html
   <!-- Footer Start -->
    <div class="container-fluid bg-dark text-secondary mt-5 pt-5">
        <div class="row px-xl-5 pt-5">
            <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
                <h5 class="text-secondary text-uppercase mb-4">Get In Touch</h5>
                <p class="mb-4"></p>
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>Agami,  Alexandria, Egypt</p>
                <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>Aya Food@gamil.com</p>
                <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>01141125185</p>
            </div>
            <div class="col-lg-8 col-md-12">
                <div class="row">
                    <div class="col-md-4 mb-5">
                        <h5 class="text-secondary text-uppercase mb-4">Quick Shop</h5>
                        <div class="d-flex flex-column justify-content-start">
                            <a class="text-secondary mb-2" href="{% url 'store:product_list' %}"><i class="fa fa-angle-right mr-2"></i>Home</a>
                            <a class="text-secondary mb-2" href="{% url 'store:products' %}"><i class="fa fa-angle-right mr-2"></i>Our Products</a>
                            <a class="text-secondary mb-2" href="{% url 'cart:cart_detail' %}"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                            <a class="text-secondary mb-2" href="{% url 'coupons:get_coupon' %}"><i class="fa fa-angle-right mr-2"></i>Copons</a>
                            <a class="text-secondary mb-2" href="{% url 'orders:order_create'%}"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                            <a class="text-secondary mb-2" href="{% url 'contactus:contactus' %}"><i class="fa fa-angle-right mr-2"></i>Contact Us</a> 
                            <a class="text-secondary mb-2" href="{% url 'seller:why_us' %}"><i class="fa fa-angle-right mr-2"></i>Sell With US</a> 
                        </div>
                    </div>
                    <div class="col-md-4 mb-5">
                        <h5 class="text-secondary text-uppercase mb-4">Our Team</h5>
                        <div class="d-flex flex-column justify-content-start">
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Ahmed Mahran </a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Akram Khalil</a>
                        



                        </div>
                    </div>
                    <div class="col-md-4 mb-5">
                        <h5 class="text-secondary text-uppercase mb-4">Newsletter</h5>
                        <h6 class="text-secondary text-uppercase mt-4 mb-3">Follow Us</h6>
                        <div class="d-flex">
                            <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                            <a class="btn btn-primary btn-square" href="#"><i class="fab fa-instagram"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row border-top mx-xl-5 py-4" style="border-color: rgba(256, 256, 256, .1) !important;">
            <div class="col-md-6 px-xl-0">
                <p class="mb-md-0 text-center text-md-left text-secondary">
                    &copy; <a class="text-primary" href="#">copywrite</a>. All Rights Reserved. Development
                    by
                    <a class="text-primary" href="#">Aya Food Team</a>
                </p>
            </div>
            <div class="col-md-6 px-xl-0 text-center text-md-right">
                <img class="img-fluid" src="img/payments.png" alt="">
            </div>
        </div>
    </div>
    <!-- Footer End -->

<a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>

templates/includes/navbar.html
 <!-- Topbar Start -->
  <div class="container-fluid" >
    <div class="row bg-secondary py-1 px-xl-5" >
        <!-- <div class="col-lg-4 col-6 text-right">
            <p class="m-0">Customer Service</p>
            <h5 class="m-0">+0100 345 6789</h5>
        </div> -->
            </div>        </div>
        <div class="col-lg-6 text-center text-lg-right" style="padding-top: 8px;">
            <div class="d-inline-flex align-items-center">
                {% if request.user.is_authenticated %}
                <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown">My Profile</button>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" type="button" href="{% url 'accounts:dashboard' %}">Profile</a>
                        <a class="dropdown-item" type="button" href="{% url 'accounts:logout' %}">Logout</a>
                    </div>
                </div>
                {% else %}
                <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown">Join US</button>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" type="button" href="{% url 'accounts:login' %}">Login</a>
                        <a class="dropdown-item" type="button" href="{% url 'accounts:register' %}">Register</a>
                    </div>
                </div>
                {% endif %}
                <div class="btn-group mx-2">
                    <button type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown">EGP</button>
                    <div class="dropdown-menu dropdown-menu-right">
                        <button class="dropdown-item" type="button">EG</button>
                    </div>
                </div>
                <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown">EN</button>
                    <div class="dropdown-menu dropdown-menu-right">
                        <button class="dropdown-item" type="button">EN</button>
                        <button class="dropdown-item" type="button">AR</button>
                    </div>
                </div>
            </div>
            <div class="d-inline-flex align-items-center d-block d-lg-none">
                
            </div>
        </div>
    </div>
    <div class="row align-items-center bg-light py-3 px-xl-5 d-none d-lg-flex">
        <div class="col-lg-4">
            <a href="{% url 'store:product_list' %}" class="text-decoration-none">
                <span class="h1 text-uppercase text-dark bg-primary px-2 ml-n1" >Aya Food <lord-icon src="https://cdn.lordicon.com/eiekfffz.json" style="width: 67px;height: 51px;/* margin-top: 7px; */padding-top: 10px;" trigger="hover"></lord-icon>                </span>
                <script src="https://cdn.lordicon.com/lordicon.js"></script>
            </a>
        </div>
        <div class="col-lg-4 col-6 text-left">

           
            <form action="{% url 'store:products' %}" method='GET'>
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for products" name="query">
                    <div class="input-group-append">
                        <button class="input-group-text bg-transparent text-primary"><i class="fa fa-search"></i>

                        </button>
                    </div>
                </div>
            </form>
        </div>
        {% if request.user.is_authenticated and user.is_admin %}
        <div class="col-lg-4 col-6 text-right">
            <p class="m-0" style="color:green;">Welcome {{user.first_name| capfirst}}</p>
            
            
        </div>
        {% else %}
        <div class="col-lg-4 col-6 text-right">
            <p class="m-0">Customer Serves</p>
            <h5 class="m-0">01141125185</h5>
        </div>
        {% endif %}
    </div>
</div>
<!-- Topbar End -->




<!-- Navbar Start -->
<div class="container-fluid bg-dark mb-30" >
    <div class="row px-xl-5" >
        <div class="col-lg-3 d-none d-lg-block" >
            <a class="btn d-flex align-items-center justify-content-between bg-primary w-100"  data-toggle="collapse" href="#navbar-vertical" style="height: 65px; padding: 0 30px;">
                <h6 class="text-dark m-0"><i class="fa fa-bars mr-2"></i>Categories</h6>
                <i class="fa fa-angle-down text-dark"></i>
            </a>
            <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 bg-light"  id="navbar-vertical" style="width: calc(100% - 30px); z-index: 999;">
                <div class="navbar-nav w-100">
                    <a href="{% url 'store:product_list' %}" class="nav-item nav-link">All Products</a>
                    {% for c in categories %}
                    <a href="{{c.get_absolute_url}}" class="nav-item nav-link">{{c.name}}</a>
                    {% endfor %}
                    
                </div>
            </nav>
        </div>
        <div class="col-lg-9">
            <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 py-lg-0 px-0" >
                <a href="" class="text-decoration-none d-block d-lg-none">
                    <span class="h1 text-uppercase text-light bg-primary px-2 ml-n1">Aya Food<i class="fas fa-shopping-cart"></i></span>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav mr-auto py-0">
                        <a href="{% url 'store:product_list' %}" class="nav-item nav-link">Home</a>
                        <a href="{% url 'store:products' %}" class="nav-item nav-link">Products</a>
                        <a href="{% url 'cart:cart_detail' %}" class="nav-item nav-link">Your Cart</a>
                        <a href="{% url 'orders:order_create' %}" class="nav-item nav-link">Checkout</a>
                        <a href="{% url 'contactus:contactus' %}" class="nav-item nav-link">Contact</a>
                        {% if request.user.is_authenticated %}
                        <a href="{% url 'accounts:dashboard' %}" class="nav-item nav-link">My Profile</a>
                        {% endif %}

                    </div>
                    <div class="navbar-nav ml-auto py-0 d-none d-lg-block">
                        
                        {% with total_items=cart|length %}
                        {% if total_items > 0 %}
                           
                        <a href="{% url 'cart:cart_detail' %}" class="btn px-0 ml-3">
                            <i class="fas fa-shopping-cart text-primary"></i>
                            <span class="badge text-secondary border border-secondary rounded-circle" style="padding-bottom: 2px;">{{ total_items }}</span>
                        </a>
                            {% else %}
                            <a href="{% url 'cart:cart_detail' %}" class="btn px-0 ml-3">
                                <i class="fas fa-shopping-cart text-primary"></i>
                                <span class="badge text-secondary border border-secondary rounded-circle" style="padding-bottom: 2px;">0</span>
                        </a>
                        {% endif %}
                        {% endwith %}
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div> 
<!-- Navbar End -->