accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('dashboard/' , views.dashboard , name='dashboard'),

    path('logout/', views.user_logout, name='logout'),
    path('dashboard/' , views.dashboard , name='dashboard'),
    path('' , views.dashboard , name='dashboard'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),
    path('resetPassword/', views.resetPassword, name='resetPassword'),

   
    ]

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail , name='cart_detail'),
    path('<int:product_id>/' , views.cart_add , name='cart_add'),
    path('remove/<int:product_id>/' , views.cart_remove , name='cart_remove'),
]

main_store/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

admin.site.index_title = "Promo"
admin.site.site_header = "Promo Admin"
admin.site.site_title = "Promo-Ecommerce"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/' , include('accounts.urls' , namespace='accounts')),
    path('contact-us/' , include('contactus.urls' , namespace='contactus')),
    path('cart/' , include('cart.urls' , namespace='cart')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('orders/' , include('orders.urls' , namespace='orders')),
    path('' , include('store.urls', namespace='store')),
    path('join-US-seller/' , include('seller.urls' , namespace='seller')),
    path('seller/account/' , include('seller_account.urls' , namespace='seller_account')),


]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path
from . import views


app_name = 'seller'


urlpatterns = [
    path('why-us/' , views.why_us , name='why_us'),
    path('download-pdf/', views.download_pdf, name='download_pdf'),
    path('dashboard' , views.dashboard , name='dashboard'),
    path('my-products/' , views.products , name='products'),
    path('successfully/' , views.successfully , name='successfully'),
    path('analytics/' , views.analytics , name='analytics'),
    path('<int:id>/update-product/' , views.update , name='update'),
    path('delete/<int:id>/' , views.delete , name='delete'),
    path('order/<int:id>/delete/', views.order_delete, name='order_delete'),





    

]

seller/models.py
from django.db import models

# Create your models here.

seller/forms.py
from django import forms
from store.models import Product
from orders.models import Order 

from django.utils.text import slugify

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'seller' ,'category', 'image', 'description', 'price', 'old_price', 'stock', 'available' ]
        widgets = {
            "name": forms.TextInput(attrs={'class': 'form-control'}),
            "seller": forms.Select(attrs={'class': 'form-control'}),
            "category": forms.Select(attrs={'class': 'form-control'}),
            "image": forms.FileInput(attrs={'class': 'form-control'}),
            "description": forms.TextInput(attrs={'class': 'form-control'}),
            "price": forms.NumberInput(attrs={'class': 'form-control'}),
            "old_price": forms.NumberInput(attrs={'class': 'form-control'}),
            "stock": forms.NumberInput(attrs={'class': 'form-control'}),
            "available": forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

    def save(self, commit=True):
        instance = super(ProductForm, self).save(commit=False)
        instance.slug = slugify(instance.name)  # Generate slug from the name field
        if commit:
            instance.save()
        return instance
    

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name' , 'last_name' , 'email' , 'address' , 'phone' , 'postal_code' , 'notes', 'city' , 'paid']

        widgets = {
            "first_name": forms.TextInput(attrs={'class': 'form-control'}),
            "last_name": forms.TextInput(attrs={'class': 'form-control'}),
            "email": forms.EmailInput(attrs={'class': 'form-control'}),
            "address": forms.TextInput(attrs={'class': 'form-control'}),
            "phone": forms.NumberInput(attrs={'class': 'form-control'}),
            "postal_code": forms.NumberInput(attrs={'class': 'form-control'}),
            "notes": forms.TextInput(attrs={'class': 'form-control'}),
            "city": forms.TextInput(attrs={'class': 'form-check-input'}),
            "paid": forms.CheckboxInput(attrs={'class': 'form-check-input'}),

        }

seller/views.py
from django.shortcuts import render , redirect , get_object_or_404
from django.http import FileResponse
from django.conf import settings
import os
from .forms import ProductForm , OrderForm
from store.models import Product
from orders.models import OrderItem , Order
from django.contrib.auth.decorators import login_required



def why_us(request):
    return render(request , 'seller/why_us.html')




def download_pdf(request):
    pdf_path = os.path.join(settings.MEDIA_ROOT, 'pdf/beginer.pdf')
    return FileResponse(open(pdf_path, 'rb'), content_type='application/pdf')



def dashboard(request , ):
    orders = OrderItem.objects.all().order_by('-created')
    context = {
        'orders':orders
    }

    return render(request , 'seller/dashboard_sell.html' , context)




@login_required
def products(request):
    seller_id = request.user.id  # Assuming seller_id is the same as user id
    if request.method == 'POST':
        add_product = ProductForm(request.POST, request.FILES)
        if add_product.is_valid():
            # Set the seller for the product before saving
            product = add_product.save(commit=False)
            product.seller_id = seller_id
            product.save()
            return redirect('seller:successfully')

    forms = ProductForm()
    # Filter products based on the seller_id
    seller_products = Product.objects.filter(seller_id=seller_id).order_by('-created')
    context = {
        'form': forms,
        'seller_products': seller_products,
    }
    return render(request, 'seller/products_seller.html', context)


def successfully(request):
    return render(request , 'seller/success.html')



@login_required
def update(request , id):
    product_id = Product.objects.get(id=id , available=True)
    if request.method == 'POST':
        product_save = ProductForm(request.POST , request.FILES , instance=product_id)
        if product_save.is_valid():
            product_save.save()
            return redirect('seller:products')
    else:
        product_save = ProductForm(instance=product_id) 
    context = {
        'form':product_save
    }           


    return render(request , 'seller/update.html' , context)


@login_required
def delete(requset , id):
    product_delete = get_object_or_404(Product , id=id , available=True)
    if requset.method == 'POST':
        product_delete.delete()
        return redirect('seller:products')
    return render(requset , 'seller/delete.html')






@login_required
def order_delete(request, id):
    # Get the order or return a 404 error if it doesn't exist
    order = get_object_or_404(OrderItem, id=id)
    
    if request.method == 'POST':
        order.delete()
        return redirect('seller:dashboard')
    context = {
        'order_id':order
    }

    return render(request, 'seller/order_delete.html' , context)



def status(request):
    orders = OrderItem.objects.all()
    
    rejections = orders.filter(status=OrderItem.Status.Rejection)
    shippings = orders.filter(status=OrderItem.Status.Shipping)
    processings = orders.filter(status=OrderItem.Status.Pending)
    
    context = {
        'orders': orders.count(),
        'rejections_count': rejections.count(),
        'shipping_count': shippings.count(),
        'processing_count': processings.count(),
        
    }

    return render(request, 'n_f_dash/status.html', context)



def analytics(request):
    return render(request , 'seller/analytics.html')

templates/seller/analytics.html
{% extends "base2.html" %}


{% block seller %}

{% include "n_f_dash/status.html" %}
<div class="row">
  <div class="card text-center col-6">
    <div class="card-header">
      Productsc - EGP
    </div>
    <div class="card-body">
      <p class="card-text"><canvas id="myChart" style="width:100%;"></canvas></p>
  
    </div>
    <div class="card-footer text-muted">
      Aya Food-Ecommerce
    </div>
  </div>
  
  
  <div class="card text-center col-6">
    <div class="card-header">
      Area Profits - EGP
    </div>
    <div class="card-body">
     
      <p class="card-text"><canvas id="mymezo" style="width:100%;max-width:100%"></canvas></p>
      
    </div>
    <div class="card-footer text-muted">
      Aya Food-Ecommerce
    </div>
  </div>
  </div>
  
  
  
{% endblock %}

templates/seller/dashboard_sell.html
{% extends "base2.html" %}
{% load static %}


{% block seller %}

{% include "n_f_dash/status.html" %}


<div class="card text-center">
  <div class="card-header">
    Orders
  </div>
  <div class="card-body">
    <h5 class="card-title">Aya Food E-Commerce</h5>
    <p class="card-text"><div class="col-md-12">
      <table class="table">
          <thead class="thead-dark">
            <tr>
              <th scope="col">Order-ID</th>
              <th scope="col">Name</th>
              <th scope="col">Product</th>

              <th scope="col">Address</th>
              <th scope="col">Status</th>
              <th scope="col">Price</th>
              <th scope="col">Date</th>
              <th scope="col">Actions</th>

            </tr>
          </thead>
          <tbody>
            {% if orders %}
            {% for order in orders %}
            
            <tr>
              <th scope="row">{{ order.id }}</th>
              <td>{{order.order.first_name}}</td>
              <td>{{order.product.name}}</td>

              <td>{{order.order.address}}</td>

              <td> <button type="button" {% if order.status == 'SHIPPING' %} class="btn btn-success btn-sm" {% elif order.status == 'PENDING' %} class="btn btn-warning btn-sm" {% elif order.status == 'REJECTION' %} class="btn btn-danger btn-sm"{% endif %} >{{order.status}}</button></td>

              <td>{{order.price}} EG</td>
              <td>{{order.order_date}}</td>
              {% comment %} <form method="post" action="{% url 'seller:order_delete' order.id %}"> {% endcomment %}
                {% csrf_token %}
                <td><a href="{% url 'seller:order_delete' order.id %}" class="btn btn-outline-danger">Remove</a></td>

            </form>
            
            </tr>
            {% endfor %}
          
          

          </tbody>
        

        </table>
        {% else %}
        <div class="alert alert-dark" role="alert">
          <h1>You Not Have Orders</h1>
        </div>

        {% endif %}
       
      </div></p>
    
  </div>
  <div class="card-footer text-muted">
    Aya Food - Ecommerce 
  </div>
</div>





  




{% endblock seller %}

templates/seller/delete.html
{% extends "base2.html" %}


{% include "n_f_dahs/status.html" %}



{% block seller %}

<div class="card mx-auto" style="max-width:520px; margin-top:40px;">
    <article class="card-body">
      <hgroup>
          <h1 style="padding-bottom: 100px;margin-bottom: -56px; padding-left:121px;" class="center">Delete Product </h1>
        </hgroup>
  
        <div>
  
    <form  method="POST" enctype="multipart/form-data" >
      {% csrf_token %}
      <div class="cart-body">
        <p> Do you need delete this Product ?</p>
  
      </div>
  
      <div><button type="submit" class="btn btn-outline-danger" style="margin-left:42%;margin-bottom: 12px;">Delete</button></div>
     <div> <a href="{% url 'seller:products' %}" class="btn btn-outline-success" style="margin-left:42%;">Cancel</a></div>

    </form>
  </div>
  </div>
  </div>
  

{% endblock seller %}

templates/seller/order_delete.html
{% extends "base2.html" %}


{% include "n_f_dahs/status.html" %}



{% block seller %}

<div class="card mx-auto" style="max-width:520px; margin-top:40px;">
    <article class="card-body">
      <hgroup>
          <h1 style="padding-bottom: 100px;margin-bottom: -56px; padding-left:121px;" class="center">Order delete </h1>
        </hgroup>
  
        <div>
  
    <form  method="POST" enctype="multipart/form-data" >
      {% csrf_token %}
      <div class="cart-body">
        <p> Do you need delete Order-ID ? <b>{{order_id}}</b></p>
  
      </div>
  
      <div><button type="submit" class="btn btn-outline-danger" style="margin-left:42%;margin-bottom: 12px;">Delete</button></div>
     <div> <a href="{% url 'seller:dashboard' %}" class="btn btn-outline-success" style="margin-left:42%;">Cancel</a></div>

    </form>
  </div>
  </div>
  </div>
  

{% endblock seller %}

templates/seller/products_seller.html
{% extends "base2.html" %}


{% block seller %}

{% include "n_f_dash/status.html" %}




<div class="card mx-auto" style="max-width:520px; margin-top:40px;">
  <article class="card-body">
    <hgroup>
        <h1 style="padding-bottom: 100px;margin-bottom: -56px; padding-left:121px;" class="center">Add Product </h1>
      </hgroup>

      <div>

  <form  method="POST"  >
    <div class="cart-body">
      {{form.as_p}}
     {% csrf_token %}

    </div>

    </div class="cart-footer">
    <button type="submit" class="btn btn-outline-primary" style="margin-left:38%;">Add Product</button>
</div>
  </form>
</div>
</div>
</div>

<br><br><br>


<p>------------------------------------------------------------------------------------------------------------------------------------<b>My - Products</b>-------------------------------------------------------------------------------------------------------------------------------------</p>


<!-- Products Start -->
<div class="container-fluid pt-5 pb-3">
  <div class="row px-xl-5">
    
   
      {% for product in seller_products %}
      <div class="col-lg-3 col-md-4 col-sm-6 pb-1">
          <div class="product-item bg-light mb-4">
              
              <div class="product-img position-relative overflow-hidden">
                  {% if product.image %}
  <!-- Display the image -->
  <img class="img-fluid w-100" src="{{product.image.url}}" alt="" style="height:400px">
  {% else %}
  <!-- Display a placeholder or alternative content -->
  No image available
{% endif %}

              </div>
          
              <div class="text-center py-4">
                  <a class="h6 text-decoration-none text-truncate" href="{{ product.get_absolute_url }}">{{ product.name}}</a>
                  <div class="d-flex align-items-center justify-content-center mt-2">
                      {% if product.stock == 0 %}
                      <h5 class="alert-danger red">Out Of Stock</h5><h6 class="text-muted ml-2"><del></del></h6>
                      {% else %} 
                      <h5>{{ product.price}} EG </h5><h6 class="text-muted ml-2"><del> {{ product.old_price }} EG</del></h6>
                      {% endif %}
                  </div>
                  <div class="d-flex align-items-center justify-content-center mb-1">
                  <div>  <a href="{% url 'seller:delete' product.id %}" class="btn btn-outline-danger" style="margin-right: 26px;">Remove</a></div>

                   <div> <a href="{% url 'seller:update' product.id  %}"  class="btn btn-outline-warning">Update</a></div>


                  </div><br>
                <b>Date</b>:   {{product.created}}<br><br>
                <a href="#" class="btn btn-primary">{{ product.seller }}</a>

                {% comment %} <h3 ><a href="#" class="badge badge-secondary"></a></h3> {% endcomment %}

                


              </div>
          </div>
      </div>
      {% endfor %}
  </div>
</div>
<!-- Products End -->

   
    
 






  
{% endblock %}

templates/seller/success.html
{% extends "base2.html" %}


{% block seller %}

<br>


<div class="text-center">
    <div class="alert alert-success"  >
        <h4 class="alert-heading">Product Added (:</h4>
        <p class="mb-0">We're So Happy To You sell With US (:</p>
        <br>
        <a href="{% url 'store:products' %}" class="btn btn-outline-success" target="_blank"><span class="text">View Products</span><i class="fas fa-eye"></i></a>
        <a href="{% url 'seller:products' %}" class="btn btn-outline-primary"><span class="text">Back Home</span><i class="fas fa-eye"></i></a>

      </div>
    </div>

{% endblock seller %}

templates/seller/update.html
{% extends "base2.html" %}



{% block seller %}


{% include "n_f_dash/status.html" %}
<div class="card mx-auto" style="max-width:520px; margin-top:40px;">
    <article class="card-body">
      <hgroup>
          <h1 style="padding-bottom: 100px;margin-bottom: -56px; padding-left:121px;" class="center">Order Update </h1>
        </hgroup>
  
        <div>
  
    <form  method="POST" enctype="multipart/form-data" >
      {% csrf_token %}
      <div class="cart-body">
        {{form.as_p}}
  
      </div>
  
      </div class="cart-footer">
      <button type="submit" class="btn btn-outline-warning" style="margin-left:42%;">Update</button>
  </div>
    </form>
  </div>
  </div>
  </div>
  
  

{% endblock seller %}

templates/seller/why_us.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="content">
    <div class="general-content" style="padding-left: 202px;">
        <h1 style="padding-right: 156px;">Welcome to sell on Aya Food</h1>
        <p style="padding-right: 185px;">It's no secret: At <b>Aya Food</b>, we're obsessed with customers. Our customers want a trusted destination where they can purchase a variety of goods - which is what makes sellers like you so important. We are always looking for ways to add value to our customers and be the most customer-focused company on Earth. As an Aya Food seller, you participate in offering these customers better selection, better prices, and a first-class customer experience.
        <p style="padding-right: 168px;"><a href="{% url 'seller:download_pdf' %}" target="_blank" class="btn btn-primary">Download e-book</a></p>
        </div>
    
    <div class="content2">
      <h1>What do you need to get started?</h1><br><br>
      <div class="reasons" style="padding: 94px;">
       
      
        <div class="non-technical">
          <ul>
            <br>
            <li class="list">1- Bank account number</li>
            <li class="list">2- Mobile Phone Number</li>
            <li class="list">3- A valid email address </li>
            <li class="list">4- Aya Food seller account </li>

         
          
          </ul>
        </div>
    </div>
  </div> 
    
    <div class="offer-list">
      <img src="{% static 'img/Aya Food.png' %}">
       <div class="level-description">
         <div class="card" style="margin-bottom: 0px;margin-top: 72px;">
            <div class="card-header">
              Let's GO Sell With Aya Food
            </div>
            <div class="card-body">
              <h5 class="card-title">Don't have an Aya Food seller account yet?</h5>
              <a href="{% url 'seller_account:register' %}" class="btn btn-primary">Register Now</a>
            </div>
          </div>

       </div>
    </div>

    
    <div class="final-remarks">
      <div class="remarks">
        <h2>This is just the beginning</h2>
        <p>The moment you sell on Aya Food is the moment you can start growing your Aya Food business. Once you launch your business, Aya Food has tools to help you take your business to the next level (or two).</p>
        <h2>Aya Foodtions and discount coupons</h2>
        <p>Customers want to save, and Aya Foodtions are an incentive to make a purchase now. There are three types of Aya Foodtions: money off, free shipping, and buy one get one free. You can also offer percentage discounts or cash off using digital coupons.</p>

        
      </div>
      <img src="{% static 'img/pro.png' %}">
    </div>
  </div>

{% endblock content %}