accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('dashboard/' , views.dashboard , name='dashboard'),

    path('logout/', views.user_logout, name='logout'),
    path('dashboard/' , views.dashboard , name='dashboard'),
    path('' , views.dashboard , name='dashboard'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),
    path('resetPassword/', views.resetPassword, name='resetPassword'),

   
    ]

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail , name='cart_detail'),
    path('<int:product_id>/' , views.cart_add , name='cart_add'),
    path('remove/<int:product_id>/' , views.cart_remove , name='cart_remove'),
]

coupons/urls.py
from django.urls import path
from . import views


app_name = 'coupons'

urlpatterns = [
    path('apply/' , views.coupon_apply , name='apply'),
    path('get-coupon/' , views.get_coupon , name='get_coupon')
]

main_store/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

admin.site.index_title = "Promo"
admin.site.site_header = "Promo Admin"
admin.site.site_title = "Promo-Ecommerce"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/' , include('accounts.urls' , namespace='accounts')),
    path('contact-us/' , include('contactus.urls' , namespace='contactus')),
    path('cart/' , include('cart.urls' , namespace='cart')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('orders/' , include('orders.urls' , namespace='orders')),
    path('' , include('store.urls', namespace='store')),
    path('join-US-seller/' , include('seller.urls' , namespace='seller')),
    path('seller/account/' , include('seller_account.urls' , namespace='seller_account')),


]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/' ,views.order_create , name='order_create'),
    path('traking-order/' , views.user_orders , name='traking'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf , name="admin_order_pdf"),
    
]

store/urls.py
from django.urls import path
from . import views



app_name = 'store'


urlpatterns = [
    path('' , views.product_list , name='product_list'),
    path('products/' , views.store , name='products'),
    path('category/<slug:category_slug>/' , views.store , name='product_by_category'),
    path('<slug:category_slug>/' , views.product_list , name='product_list_by_category'),
    path('<int:id>/<slug:slug>/' , views.product_detail , name='product_detail'),
    path('<int:product_id>/comment/' , views.product_comment , name='product_comment')
    

]

coupons/models.py
from django.db import models
from django.core.validators import MinValueValidator , MaxValueValidator



class Coupon(models.Model):
    code = models.CharField(max_length=50 , unique=True)
    valid_from = models.DateTimeField()
    valid_to = models.DateTimeField()
    discount = models.IntegerField(validators=[MinValueValidator(0) , MaxValueValidator(100)] , help_text="Percentage value (0 to 100)") # this is a percentage, so it takes values from 0 to 100%
    active = models.BooleanField()

    def __str__(self):
        return self.code

store/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings





class Category(models.Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField(unique=True , max_length=250)
    image = models.ImageField(upload_to='category/%Y/%m/%d' , blank=True)


    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name'])
        ]

        verbose_name = 'category'
        verbose_name_plural = 'Categories'



    def __str__(self):
        return self.name
    
    
    def get_absolute_url(self):
        return reverse("store:product_by_category", args=[self.slug])
    
    




class Product(models.Model):
    category = models.ForeignKey(Category , related_name="products" , on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    seller = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='seller',on_delete=models.CASCADE , null=True)
    slug = models.SlugField(unique=True , max_length=250)
    image = models.ImageField(upload_to='products/%Y/%m/%d' , blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10 , decimal_places=2)
    old_price = models.DecimalField(max_digits=10 , decimal_places=2)
    stock = models.IntegerField(default=0)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id' , 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.id, self.slug])
    




class Comments(models.Model):
    product = models.ForeignKey(Product , on_delete=models.CASCADE , related_name='comments')
    name = models.CharField(max_length=100)
    email = models.EmailField()
    content = models.TextField(blank=True , null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name = "Comments"
        verbose_name_plural = "Comments"


    def __str__(self):
        return f'{self.name} By {self.product}'

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created'])
        ]   

    def __str__(self):
        return f'Comment by {self.name} on {self.product}'    

























class VariationManager(models.Manager):
    # Just get color    
    def get_color(self):
        return super(VariationManager , self).filter(Variation_category='color' , is_active=True)
    # just get size
    def get_size(self):
        return super(VariationManager , self).filter(Variation_category='size' , is_active=True)


Variation_category_choices =(
    ('color' , 'color'),
    ('size' , 'size'),
)




class Variation(models.Model):
    product = models.ForeignKey(Product , on_delete=models.CASCADE)
    Variation_category = models.CharField(max_length=100 , choices=Variation_category_choices)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    
    created_date = models.DateTimeField(auto_now=True)
    
    objects = VariationManager()

















# class Comment(models.Model):
#     product = models.ForeignKey(Product , on_delete=models.CASCADE , related_name='comments')
#     name = models.CharField(max_length=100)
#     email = models.EmailField()
#     body = models.TextField()
#     created = models.DateTimeField(auto_now_add=True)
#     updated = models.DateTimeField(auto_now=True)
#     active = models.BooleanField(default=True)

#     class Meta:
#         ordering = ['created']
#         indexes = [
#             models.Index(fields=['created'])
#         ]

#     def __str__(self):
#         return f'Comment by {self.name} on {self.product}'     

coupons/forms.py
from django import forms


class CouponApplyForm(forms.Form):
    code = forms.CharField(max_length=100 , widget=forms.TextInput(attrs={
    'placeholder':"Coupon Code",
     'class':"form-control border-0 p-4",

    }))

store/forms.py
from django import forms 
from .models import Comments



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['name' , 'email' , 'content']

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control' , 'placeholder':'Your Name'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder':'Your Email'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'placeholder':'Comment'}),
        }


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name in self.fields:
            self.fields[field_name].label = False

coupons/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from django.views.decorators.http import require_POST
from .models import Coupon
from .forms import CouponApplyForm




@require_POST
def coupon_apply(request):
    now = timezone.now()
    form = CouponApplyForm(request.POST)
    if form.is_valid():
        code = form.cleaned_data['code']  # stored date 
        try:
            coupon = Coupon.objects.get(code__iexact=code , valid_from__lte=now , valid_to__gte=now , active=True)
            request.session['coupon_id'] = coupon.id   # stores it in the user’s session.
        except Coupon.DoesNotExist: 
            request.session['coupon_id'] = None
    return redirect('cart:cart_detail')         





def get_coupon(request):
    coupons = Coupon.objects.all()

    return render(request , 'store/coupons.html' , {'coupons':coupons})

store/views.py
from django.shortcuts import render , get_object_or_404
from .models import Category , Product
from cart.forms import CartAddProductForm
from django.contrib.postgres.search import SearchVector
from django.views.decorators.http import require_POST
from .forms import CommentForm


def product_list(request , category_slug=None):
    MAX_PRODUCTS = 8
    category = None
    categories = Category.objects.all()
    products = Product.objects.all().filter(available=True).order_by('-created')[:MAX_PRODUCTS]
    if category_slug:
        category = get_object_or_404(Category , slug=category_slug)
        products = products.filter(category=category)
    context = {
        'categories':categories,
        'category':category,
        'products':products,
    }    
    return render(request , 'store/home.html' , context)





def product_detail(request , id , slug):
    product = get_object_or_404(Product , id=id , slug=slug , available=True)
    cart_product_form = CartAddProductForm()
    comments = product.comments.filter(active=True)
    form = CommentForm()
    context = {
        'product':product,
        'cart_product_form':cart_product_form,
        'comments':comments,
        'form':form,
        
    }
    return render(request , 'store/product_detail.html' , context)





def store(request , category_slug=None) -> None:
    category = None
    categories = Category.objects.all()
    products = Product.objects.all().filter(available=True).order_by('-created')
    if category_slug:
        category = get_object_or_404(Category , slug=category_slug)
        products = products.filter(category=category)
    # hendle search  
    name = None
    price_form = None
    price_to = None
    if 'query' in request.GET:
        name = request.GET['query'] 
        if name: # check name is exsist ?
            products = products.filter(name__icontains=name) 
    
    if 'searchpricefrom' in request.GET and 'searchpriceto' in request.GET:
        price_form = request.GET['searchpricefrom']
        price_to = request.GET['searchpriceto']
        if price_form and price_to:  # check price is exsist ?
            if price_form.isdigit() and price_to.isdigit(): # check price is digit !
                products = products.filter(price__gte=price_form , price__lte=price_to)

   
    context = {
        'categories':categories,
        'category':category,
        'products':products,
    }

    return render(request, 'store/store.html' , context)

"""
We use the require_POST decorator provided by Django to
only allow POST requests for this view 
"""


@require_POST
def product_comment(request , product_id):
    prodcut = get_object_or_404(Product , id=product_id , available=True)
    comment = None

    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.prodcut = prodcut
        comment.save()
    context = {
        'form':form,
        'comment':comment, 
        'product':prodcut,
    }    

    return render(request , 'sotre/comment.html' , context)

templates/store/cart_detail.html
{% extends "base.html" %}



{% block content %}


    <!-- Cart Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                        <tr>
                            <th>Products</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Total</th>
                            <th>Remove</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">

                   


                        
                        {% for item in cart %}
                        {% with product=item.product %}
                        
                        <tr>
                           <td class="align-middle" style="width: 100px"><a href="{{ product.get_absolute_url }}">
                            {% if product.image %}
                                
                               
                            <img src="{{ product.image.url }}" alt="loading" style="width: 50px;">{{ product.name }}</a>
                               {% else %}
                               <img class="img-fluid w-100" src="#" alt="logo" style="height:400px;">


                               {% endif %}
                          </td>
<!--                 
                            <td class="align-middle"> Brown</td>
                            <td class="align-middle">X-Larg</td> -->


                            <td class="align-middle">{{ product.price }} EG</td>
                            <td class="align-middle">
                                <form action="{% url "cart:cart_add" product.id %}" method="post" >
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.override }}
                                    {% comment %} <input type="submit" value="Update" class="btn-success"> {% endcomment %}
                                    <input type="submit" value="Update" class="btn btn-outline-warning">

                                    {% csrf_token %}
                                </form>
                            
                            </td>
                            <td class="align-middle">{{ item.total_price }} EG</td>
                            
                            <td class="align-middle">
                                <form action="{% url "cart:cart_remove" product.id %}" onclick="return confirm('Are you sure you want to delete this item?')" method="post">
                               <input type="submit"  value="Remove" class="btn btn-outline-danger">

                                {% csrf_token %}
                                </form>
                                </td>
                        </tr>
                        {% endwith %}
                        {% endfor %}
                        
                    </tbody>
                    
                </table>
            </div>


            
            <div class="col-lg-4">

                <form class="mb-30" action="{% url "coupons:apply" %}" method="POST">
                    {% csrf_token %}
                    <div class="input-group">
                        {{ coupon_apply_form }}
                        <div class="input-group-append">
                            <button class="btn btn-primary">Apply Coupon</button>
                        </div>
                    </div>
                </form>



                <h5 class=""><span class="bg-secondary pr-3">Cart Summary</span>
                 
            
                </h5>
                <div class="bg-light p-30 mb-5">
                    <div class="border-bottom pb-2">
                       
                        
                       {% if cart.coupon %}
                        <div class="d-flex justify-content-between mb-3">
                            <h6>Subtotal</h6>
                            <h6>{{ cart.get_total_price }} EG</h6>
                        </div>
                        <div class="d-flex justify-content-between mb-3">
                            <h6>Discount Code</h6>
                            <h6 style="color:green;">
                                "{{ cart.coupon.code }}" coupon
                                ({{ cart.coupon.discount }}% off)
                            </h6>

                        </div>
                        <div class="d-flex justify-content-between mb-3">
                            <h6>Discount</h6>
                            <h6 style="color:red;">{{ cart.get_discount|floatformat:2 }} - EG</h6>
                        </div>
                     

                        <div class="d-flex justify-content-between mb-3">
                            <h6>Tax</h6>
                            <h6>{{ tax }} EG</h6>
                        </div>
                        <div class="d-flex justify-content-between">
                        {% with total_items=cart|length %}
                        {% if total_items > 0 %}
                              <h6>Items Amount </h6> 
                              <h6>{{ total_items }}</h6>
                            {% elif not order %}
                            <div class="alert alert-dark" role="alert">
                                Your cart is empty ):  <a href="{% url 'store:products' %}" class="alert-link">Go Shipping</a>. 
                              </div>
                          
                            {% endif %}
                            {% endwith %}  
                        </div>
                    </div>
                    <div class="pt-2">
                        <div class="d-flex justify-content-between mt-2">
                            <h5>Total</h5>
                            <h5>{{ cart.total_after_discount_with_tax|floatformat:2 }} EG</h5>
                        </div>
                        <a href="{% url "orders:order_create"%}" class="btn btn-block btn-primary font-weight-bold my-3 py-3"> Checkout</a>
                       

                    </div>


                    {% else %}
                    
                    <div class="bg-light p-30 mb-5">
                        <div class="border-bottom pb-2">
                           
                            
                           
                            <div class="d-flex justify-content-between mb-3">
                                <h6>Subtotal</h6>
                                <h6>{{ total_price }} EG</h6>
                            </div>
                            <div class="d-flex justify-content-between mb-3">
                                <h6>Tax</h6>
                                <h6>{{ tax }} EG</h6>
                            </div>
                            <div class="d-flex justify-content-between">
                            {% with total_items=cart|length %}
                            {% if total_items > 0 %}
                                  <h6>Items Amount </h6> 
                                  <h6>{{ total_items }}</h6>
                                {% elif not order %}
                                <div class="alert alert-dark" role="alert">
                                    Your cart is empty ):  <a href="{% url 'store:products' %}" class="alert-link">Go Shipping</a>. 
                                  </div>
                              
                                {% endif %}
                                {% endwith %}  
                            </div>
                        </div>
                        <div class="pt-2">
                            <div class="d-flex justify-content-between mt-2">
                                <h5>Total</h5>
                                <h5>{{ total }} EG</h5>
                            </div>
                            {% if request.user.is_authenticated %}
                            <a href="{% url "orders:order_create"%}" class="btn btn-block btn-primary font-weight-bold my-3 py-3"> Checkout</a>
                            {% else %}
                            <a href="{% url "accounts:register"%}" class="btn btn-block btn-primary font-weight-bold my-3 py-3"> Checkout</a>
                            {% endif %}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <!-- Cart End -->

{% endblock content %}

templates/store/comment.html
{% block content %}

{% if comment %}
<h2>Your comment has been added.</h2>
<p><a href="{{ product.get_absolute_url }}">Back to the Product</a></p>
{% else %}
{% include "includes/comment_form.html" %}
{% endif %}

{% endblock content %}

templates/store/coupons.html
{% extends "base.html" %}

{% block content %}
<h1 style="padding-left: 45%;" class="brown card-title">Coupons</h1>
<table class="table table-sm table-dark">
    <thead>
      <tr>
        <th scope="col">Coupon Name</th>
        <th scope="col">Discount</th>
        <th scope="col">Valid Date</th>
        <th scope="col">End Date</th>
      </tr>
   
    </thead>
    
    <tbody>
      {% for coupon in coupons %}
      <tr>
        <th scope="col">{{coupon.code}}</th>
        <th scope="col">{{coupon.discount}}%</th>
        <th scope="col">{{coupon.valid_from}}</th>
        <th scope="col">{{coupon.valid_to}}</th>
      </tr>
      {% endfor %}
     
    
    </tbody>
  </table>


{% endblock content %}

templates/store/store.html
{% extends "base.html" %}
{% load static %}
{% block content %}


    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="{% url 'store:product_list' %}">Home</a>
                    <a class="breadcrumb-item text-dark" href="{% url 'store:products' %}">Stores</a>
                    <span class="breadcrumb-item active">Products</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Shop Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <!-- Shop Sidebar Start -->
            <div class="col-lg-3 col-md-4">
                <!-- Price Start -->
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Filter by price</span></h5>
                <div class="bg-light p-4 mb-30">


                    <form action="{% url 'store:products' %}" method="GET" >
                        <!-- Minimum value input field -->
                        <div class="form-group mb-3">
                            <input type="number" class="form-control" id="price-all" placeholder='10 EG' name="searchpricefrom">
                        </div>
                    
                        <!-- Maximum value input field -->
                        <div class="form-group mb-3">
                            <input type="number" class="form-control" id="price-1"  placeholder='100 EG' name="searchpriceto">
                        </div>
                          <!-- Submit button -->
                          {% comment %} <button type="button" class="btn btn-primary btn-sm">Small button</button> {% endcomment %}
                          <button style="" type="submit" class="btn btn-primary">Apply</button>
                    </form>
                </div>
                <!-- Price End -->
                
                <!-- Color Start -->
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Categories</span></h5>
                <div class="bg-light p-4 mb-30">
                    <div class="filter__controls">
                    {% for c in categories %}
                    <a href="{{c.get_absolute_url}}" class="form-control" style="color:orange;">{{c.name}}</a>
                    {% endfor %}
                    </div>
                </div>
                <!-- Color End -->

            </div>
            <!-- Shop Sidebar End -->


            <!-- Shop Product Start -->
            <div class="col-lg-9 col-md-8">
                <div class="row pb-3">

                   {% if products %}
                    {% for product in products %}
                    <div class="col-lg-3 col-md-4 col-sm-6 pb-1">
                       
                        <div class="product-item bg-light mb-4">
                           
                            
                            <div class="product-img position-relative overflow-hidden">
                                {% if product.image %}
                                
                               
                               <img class="img-fluid w-100" src="{{product.image.url}}" alt="logo" style="height:400px;">
                               {% else %}
                               <img class="img-fluid w-100" src="#" alt="logo" style="height:400px;">


                               {% endif %}
                                <div class="product-action">                                    
                                </div>
                            </div>
                            <div class="text-center py-4">
                                <a class="h6 text-decoration-none text-truncate" href="{{ product.get_absolute_url }}">{{ product.name}}</a>
                                <div class="d-flex align-items-center justify-content-center mt-2">
                                    {% if product.stock == 0 %}
                                    <h5 class="alert-danger">Out Of Stock</h5><h6 class="text-muted ml-2"><del></del></h6>
                                    {% else %} 
                                    <h5>{{ product.price}} EG</h5><h6 class="text-muted ml-2"><del>{{ product.old_price }} EG</del></h6>
                                    {% endif %}
                                </div>
                                <div class="d-flex align-items-center justify-content-center mb-1">
                                    <small class="fa fa-star text-primary mr-1"></small>
                                    <small class="fa fa-star text-primary mr-1"></small>
                                    <small class="fa fa-star text-primary mr-1"></small>

                                    
                                    <small>(3)</small>
                                </div>
                                <a class="h6 text-decoration-none text-truncate" href="{{ product.get_absolute_url }}" >
                                    <span class="badge badge-pill badge-success">{{ product.seller}}</span></a>

                            </div>
                        </div>
                       
                    </div>
                  
                    {% endfor %}
                    {% else %}
                    <div class="alert alert-warning d-flex align-items-center" role="alert" style="padding-right: 1107px;">
                        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Warning:"><use xlink:href="#exclamation-triangle-fill"/></svg>
                        <div>
                         <h1> Not Found </h1>
                        </div>
                    </div>
                    {% endif %}

                    
                  
                    
                   
                    
                   
                    
                     
                    {% comment %} <div class="col-12">
                        <nav>
                          <ul class="pagination justify-content-center">
                            <li class="page-item disabled"><a class="page-link" href="#">Previous</span></a></li>
                            <li class="page-item active"><a class="page-link" href="#">1</a></li>
                            <li class="page-item"><a class="page-link" href="#">2</a></li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item"><a class="page-link" href="#">Next</a></li>
                          </ul>
                        </nav>
                    </div> {% endcomment %}
                </div>
            </div>
            <!-- Shop Product End -->
        </div>
    </div>
    <!-- Shop End -->


{% endblock content %}