accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('dashboard/' , views.dashboard , name='dashboard'),

    path('logout/', views.user_logout, name='logout'),
    path('dashboard/' , views.dashboard , name='dashboard'),
    path('' , views.dashboard , name='dashboard'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),
    path('resetPassword/', views.resetPassword, name='resetPassword'),

   
    ]

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail , name='cart_detail'),
    path('<int:product_id>/' , views.cart_add , name='cart_add'),
    path('remove/<int:product_id>/' , views.cart_remove , name='cart_remove'),
]

main_store/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

admin.site.index_title = "Promo"
admin.site.site_header = "Promo Admin"
admin.site.site_title = "Promo-Ecommerce"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/' , include('accounts.urls' , namespace='accounts')),
    path('contact-us/' , include('contactus.urls' , namespace='contactus')),
    path('cart/' , include('cart.urls' , namespace='cart')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('orders/' , include('orders.urls' , namespace='orders')),
    path('' , include('store.urls', namespace='store')),
    path('join-US-seller/' , include('seller.urls' , namespace='seller')),
    path('seller/account/' , include('seller_account.urls' , namespace='seller_account')),


]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path
from . import views


app_name = 'seller'


urlpatterns = [
    path('why-us/' , views.why_us , name='why_us'),
    path('download-pdf/', views.download_pdf, name='download_pdf'),
    path('dashboard' , views.dashboard , name='dashboard'),
    path('my-products/' , views.products , name='products'),
    path('successfully/' , views.successfully , name='successfully'),
    path('analytics/' , views.analytics , name='analytics'),
    path('<int:id>/update-product/' , views.update , name='update'),
    path('delete/<int:id>/' , views.delete , name='delete'),
    path('order/<int:id>/delete/', views.order_delete, name='order_delete'),





    

]

store/urls.py
from django.urls import path
from . import views



app_name = 'store'


urlpatterns = [
    path('' , views.product_list , name='product_list'),
    path('products/' , views.store , name='products'),
    path('category/<slug:category_slug>/' , views.store , name='product_by_category'),
    path('<slug:category_slug>/' , views.product_list , name='product_list_by_category'),
    path('<int:id>/<slug:slug>/' , views.product_detail , name='product_detail'),
    path('<int:product_id>/comment/' , views.product_comment , name='product_comment')
    

]

templates/n_f_dash/navbar.html
{% load static %}
<!-- jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- Bootstrap JavaScript -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'seller:dashboard' %}" style="padding-left: 28px;padding-bottom: 33px;"><b>Aya Food-Dashboard<b>

    </b></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'seller:dashboard' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'seller:products'  %}">Products</a>
        </li>
        
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               Actions
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'seller:analytics' %}">Analytics</a>
            </div>
          </li>
          {% if request.user.is_authenticated %}

          <li class="nav-item dropdown" style="padding-left:1310px">
            <h6 style="color:white;"> Hello {{ request.user.username|default:request.user.username }}</h6>


            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               Actions
            </a>

            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item selected" href="{% url 'seller_account:dashboard' %}">Profile</a>
              <a class="dropdown-item" href="{% url 'seller_account:logout' %}">Logout</a>
              <a class="dropdown-item" href="{% url 'seller_account:password_change' %}">Change Password</a>




            </div>

            {% else %}
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'seller_account:register' %}">Register</a>
              <a class="dropdown-item" href="{% url 'seller_account:login' %}">Login</a>

            </div>
            {% endif %}
          </li>
        </div>
       
      </ul>
     
    </div>
    
  </nav>
  <script>
    $(document).ready(function(){
        // Initialize Bootstrap dropdowns
        $('.dropdown-toggle').dropdown();
    });
</script>

templates/n_f_dash/status.html
{% load static %}
<br><br>
<div class="row">
    <div class="col">
        <div class="col-md" style="padding-left: 12px;">
            <div class="card text-center text-white mb-3" id="total-order">
                <div class="card-header">
                    <h5 class="card-title text-dark">Total Orders</h5>
                </div>
                <div class="card-body">
                    <a href="#" class="btn btn-primary"><b>{{ orders.count }}</b></a>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="col-md" style="padding-left: 12px;">
            <div class="card text-center text-white mb-3" id="total-order">
                <div class="card-header">
                    <h5 class="card-title text-dark">Orders Shipping</h5>
                </div>
                <div class="card-body">
                    <a href="#" class="btn btn-success"><b>{{ shipping_count }}</b></a>
                </div>
                
            </div>
        </div>
    </div>
    <div class="col">
        <div class="col-md" style="padding-left: 12px;">
            <div class="card text-center text-white mb-3" id="total-order">
                <div class="card-header">
                    <h5 class="card-title text-dark">Orders Rejection</h5>
                </div>
                <div class="card-body">
                    <a href="#" class="btn btn-danger"><b>{{ rejections_count.count }}</b></a>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="col-md" style="padding-right: 12px;">
            <div class="card text-center text-white mb-3" id="order-pending">
                <div class="card-header">
                    <h5 class="card-title text-dark">Orders Pending</h5>
                </div>
                <div class="card-body">
                    <a href="#" class="btn btn-warning"><b>{{ processing_count }}2</b></a>
                </div>
            </div>
        </div>
    </div>
</div>